name: React CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Or use a specific LTS version like '20.11.1'

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🛠️ Build the Project
        run: npm run build

      - name: ✅ Run Tests (Optional)
        run: npm test --if-present

      # OPTIONAL: Deploy to GitHub Pages
      # Uncomment below to enable automatic deployment to GitHub Pages
      #
      # - name: 🚀 Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./build
